### ISSUE TITLE
403 Access Forbidden trying to create the structure section/subsection/file

### ISSUE THREAD

**Issue by rmarins** [hguerrero/3scale-cms#4] opened 2020-07-30 01:59 UTC
Using: *3scale-2.8.1.GA-onprem* on *OCP 4.4.12*

Trying to upload file with following structure `topics/api-management/open-banking.html.liquid` fails. This folder and sub-folder structure doesn't exist as Developer Portal sections hierarchy.

```shell
[user@localhost tmp]$ cms <PROVIDER_KEY> <URL> upload topics/api-management/open-banking.html.liquid 

Loaded ignore file list from '/tmp/.cmsignore'
Analyzing local files under '/tmp'
Getting CMS content from https://domain.com/admin/api/cms 

Failed to create 'topics/api-management/open-banking.html.liquid': Failed to create required section 'topics' for 'topics/api-management/open-banking.html.liquid' : 403 Forbidden
```

**Comment by rmarins** [comment] 2020-07-30 02:03
After manually creating the `topics/api-management` sections hierarchy, the command above successfully completed.

```shell
[user@localhost tmp]$ cms <PROVIDER_KEY> <URL> upload topics/api-management/open-banking.html.liquid 

Loaded ignore file list from '/tmp/.cmsignore'
Analyzing local files under '/tmp'
Getting CMS content from https://domain.com/admin/api/cms 

Failed to create 'topics/api-management/open-banking.html.liquid': Failed to create required section 'topics' for 'topics/api-management/open-banking.html.liquid' : 403 Forbidden

The layout 'main_layout' in file 'l_main_layout.html.liquid' was selected as the default layout for uploading new pages
Created template '/topics/api-management/open-banking' in CMS with id='214' in section 'topics/api-management', timestamp '2020-07-30T02:01:33Z'
```

**Comment by neoxu9999** [comment] 2022-03-16 23:37
Hi @hguerrero , I got the same error. Is it possible to turn on the logs? I didn't see any debug model or the response from cms command.

**Comment by hguerrero** [comment] 2022-03-24 13:21
Duplicate of #3

**Closed as completed by hguerrero** 2022-03-24 13:21 UTC
